name: Build and Upload Executables

on:
  release:
    types:
      - published  # parte solo quando viene pubblicata una release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      # Build PyInstaller Linux/macOS
      - name: Build executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          pyinstaller --noconfirm --onefile scripts/build.py
        shell: bash

      # Build PyInstaller Windows
      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --noconfirm --onefile scripts\build.py
        shell: powershell

      # Zip Linux/macOS
      - name: Zip executables (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist_zip
          zip -r dist_zip/myapp-${{ matrix.os }}.zip dist/*
        shell: bash

      # Zip Windows
      - name: Zip executables (Windows)
        if: runner.os == 'Windows'
        run: |
          if (-Not (Test-Path dist)) { Write-Error "dist folder does not exist!"; exit 1 }
          New-Item -ItemType Directory -Force dist_zip
          Compress-Archive -Path .\dist\* -DestinationPath .\dist_zip\myapp-${{ matrix.os }}.zip
        shell: powershell

      # Controllo file zip creati
      - name: Check zip files
        run: |
          if (Test-Path dist_zip) { ls dist_zip } else { Write-Error "dist_zip folder not found!" }
        shell: bash

      # Upload degli asset nella release
      - name: Upload executables to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist_zip/myapp-${{ matrix.os }}.zip
          asset_name: myapp-${{ matrix.os }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
