name: Build and Release Executables

on:
  push:
    tags:
      - 'v*.*.*'  # attiva il workflow solo sui tag semver

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Run build script on Linux/macOS
        if: runner.os != 'Windows'
        run: python scripts/build.py
        shell: bash

      - name: Run build script on Windows
        if: runner.os == 'Windows'
        run: python scripts\build.py
        shell: powershell

      - name: Upload executables as artifact (temporary)
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: executables-ubuntu-latest
          path: dist/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: executables-macos-latest
          path: dist/macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: executables-windows-latest
          path: dist/windows

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: "Release automatically generated with executables for Linux, macOS and Windows."

      - name: Upload Linux executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/linux/myapp-linux.zip
          asset_name: myapp-linux.zip
          asset_content_type: application/zip

      - name: Upload macOS executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/macos/myapp-macos.zip
          asset_name: myapp-macos.zip
          asset_content_type: application/zip

      - name: Upload Windows executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/windows/myapp-windows.zip
          asset_name: myapp-windows.zip
          asset_content_type: application/zip
